kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0b9067552cbcfe58c
  basePath: "/roboshop"
  directoryPerms: "755"
reclaimPolicy: Delete